/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 29/07/2021 09:51:07
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 48000
#define MX_SYSCLKFreq_VALUE                     64000000
#define MX_HCLKFreq_Value                       64000000
#define MX_FCLKCortexFreq_Value                 64000000
#define MX_CortexFreq_Value                     64000000
#define MX_AHBFreq_Value                        64000000
#define MX_APBFreq_Value                        64000000
#define MX_CECFreq_Value                        32786
#define MX_I2S1Freq_Value                       64000000
#define MX_PWRFreq_Value                        64000000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        16000000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    64000000
#define MX_TIM1Freq_Value                       64000000
#define MX_LPUART1Freq_Value                    64000000
#define MX_TIM15Freq_Value                      64000000
#define MX_LPTIM2Freq_Value                     64000000
#define MX_USART1Freq_Value                     64000000
#define MX_LPTIM1Freq_Value                     64000000
#define MX_ADCFreq_Value                        64000000
#define MX_APBTimFreq_Value                     64000000
#define MX_SYSCLKFreq_VALUE1                    64
#define MX_SYSCLKFreq_VALUE2                    64
#define MX_USART2Freq_Value                     64000000
#define MX_I2C1Freq_Value                       64000000

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */

